version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.1-fpm-alpine
    container_name: php
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
      - redis
      - elasticsearch

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel

  redis:
    image: redis:alpine
    container_name: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
